import { Eyebrow, PageShell, ReviewSpot } from "../components/MarketingShell";

export default function HomePage(){return <PageShell>
<section className="relative overflow-hidden border-b border-emerald-400/20 px-6 py-20 md:py-28"><div className="absolute inset-x-0 top-0 mx-auto h-64 max-w-4xl rounded-full bg-emerald-400/10 blur-3xl"/><div className="relative mx-auto max-w-5xl text-center"><Eyebrow>Winston-Salem web design • business web apps</Eyebrow><h1 className="text-5xl font-black tracking-tight md:text-7xl">Your Business.<br/><span className="text-emerald-400">In Their Pocket.</span></h1><p className="mt-6 text-lg font-black tracking-wide text-emerald-300 md:text-2xl">Big-business polish. Small-business pricing.</p><p className="mx-auto mt-4 max-w-3xl text-lg leading-8 text-slate-300 md:text-xl"><strong className="text-white">Professional doesn&apos;t have to mean expensive.</strong> APPTLY builds affordable small-business websites, business web apps and digital business cards around your business, customers and brand.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><a href="/work" className="rounded-xl bg-emerald-400 px-6 py-3.5 font-black text-slate-950">See What We Build</a><a href="/services" className="rounded-xl border border-white/20 bg-white/5 px-6 py-3.5 font-black">Services & Pricing</a></div></div></section>
<section className="px-6 py-16"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3"><div className="rounded-3xl border border-white/10 bg-slate-900 p-7"><h2 className="text-xl font-black text-emerald-400">Done For You</h2><p className="mt-3 leading-7 text-slate-300">You tell us about your business. APPTLY handles the design and build.</p></div><div className="rounded-3xl border border-white/10 bg-slate-900 p-7"><h2 className="text-xl font-black text-emerald-400">One Upfront Price</h2><p className="mt-3 leading-7 text-slate-300">Packages from $99 to $449 with no required APPTLY monthly maintenance fee.</p></div><div className="rounded-3xl border border-white/10 bg-slate-900 p-7"><h2 className="text-xl font-black text-emerald-400">Real Working Projects</h2><p className="mt-3 leading-7 text-slate-300">See live work for salons, churches, local stores and entertainment businesses.</p></div></div></section>
<section className="border-y border-white/10 bg-slate-900 px-6 py-16"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[1fr_1fr] md:items-center"><div><Eyebrow>Built for small business</Eyebrow><h2 className="text-3xl font-black md:text-5xl">A real website, not one endless sales page.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Explore APPTLY the way you would any professional business site: view the portfolio, compare services and pricing, learn how the process works, and read independent evaluations on dedicated pages.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/why-apptly" className="rounded-xl border border-white/20 px-5 py-3 font-black">Why APPTLY</a><a href="/reviews" className="rounded-xl border border-white/20 px-5 py-3 font-black">Reviews</a></div></div><ReviewSpot source="ChatGPT · Independent evaluation" score="9/10 concept" quote="Very sensible for small local businesses." note="Independent evaluation based on APPTLY's public business, pricing and product information."/></div></section>
<section className="px-6 py-16"><div className="mx-auto max-w-7xl"><Eyebrow>Start where you want</Eyebrow><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["Our Work","Open live APPTLY projects and see what customers actually use.","/work"],["Services & Pricing","Compare the $99, $199, $299 and $449 packages.","/services"],["Why APPTLY","See the thinking behind the done-for-you small-business model.","/why-apptly"],["Reviews","Read independent evaluations and verified customer feedback.","/reviews"]].map(([t,c,h])=><a href={h} key={h} className="rounded-3xl border border-white/10 bg-slate-900 p-7 transition hover:-translate-y-1 hover:border-emerald-400/50"><h2 className="text-xl font-black">{t}</h2><p className="mt-3 leading-7 text-slate-300">{c}</p><span className="mt-5 inline-block font-black text-emerald-400">Explore →</span></a>)}</div></div></section>
<section className="border-t border-emerald-400/20 bg-emerald-400/5 px-6 py-16 text-center"><Eyebrow>Ready when you are</Eyebrow><h2 className="text-3xl font-black md:text-5xl">Put your business in their pocket.</h2><p className="mx-auto mt-4 max-w-2xl text-lg text-slate-300">Choose the package that best fits what you need and begin your APPTLY project.</p><a href="/services" className="mt-7 inline-flex rounded-xl bg-emerald-400 px-6 py-3.5 font-black text-slate-950">Choose Your Package →</a></section>
</PageShell>}
